# Generated by Django 3.0.3 on 2020-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='not mentioned', max_length=30)),
                ('chapter_story', models.CharField(max_length=500)),
                ('chpater_story_alternative', models.FileField(upload_to='')),
                ('chapter_number', models.IntegerField()),
                ('chapter_upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=30)),
                ('story_descrtiption', models.TextField()),
                ('story_title_pic', models.ImageField(default='default.jpg', upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('love', 'love'), ('action', 'action'), ('adventure', 'adventure')], max_length=20)),
            ],
        ),
    ]
