# Generated by Django 3.0.3 on 2020-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chappter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=30)),
                ('chapter_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(blank=True, default='not mentioned', max_length=30)),
                ('chapter_story', models.FileField(upload_to='media/')),
                ('chapter_number', models.IntegerField()),
                ('chapter_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='chapter',
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_title_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
