# Generated by Django 3.0.3 on 2020-07-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0002_auto_20200703_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='chappter',
            name='chapter_image',
            field=models.FileField(default='image not available', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_title_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
