# Generated by Django 3.0.3 on 2020-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0003_auto_20200704_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chappter',
            name='chapter_image',
            field=models.FileField(default='image not available', upload_to=''),
        ),
        migrations.AlterField(
            model_name='chappter',
            name='chapter_story',
            field=models.FileField(upload_to=''),
        ),
    ]
