# Generated by Django 3.0.3 on 2020-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0004_auto_20200704_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chappter',
            name='chapter_image',
            field=models.ImageField(default='image not available', upload_to=''),
        ),
    ]
