# Generated by Django 3.0.3 on 2020-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0007_auto_20200704_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=30)),
                ('chapter_name', models.CharField(max_length=40)),
                ('chapter_number', models.CharField(max_length=5)),
                ('commenter_name', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
