# Generated by Django 3.0.3 on 2020-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chappter',
            name='chapter_description',
            field=models.CharField(default='not mentioned', max_length=50),
        ),
    ]
