# Generated by Django 3.0.3 on 2020-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0009_chappter_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chappter',
            name='chapter_description',
            field=models.CharField(default=' chapter description not mentioned', max_length=50),
        ),
    ]
