# Generated by Django 3.0.3 on 2020-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0011_auto_20200706_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_chappter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=30)),
                ('chapter_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(blank=True, default='not mentioned', max_length=30)),
                ('chapter_description', models.CharField(default='chapter description not mentioned', max_length=500)),
                ('chapter_story', models.FileField(upload_to='')),
                ('chapter_image', models.ImageField(upload_to='')),
                ('chapter_number', models.CharField(max_length=5)),
                ('chapter_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='audio_story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=30)),
                ('story_descrtiption', models.TextField()),
                ('story_title_pic', models.ImageField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
