# Generated by Django 3.0.3 on 2020-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0012_audio_chappter_audio_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_story',
            name='story_title_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
