# Generated by Django 3.0.3 on 2020-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0013_auto_20200706_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_story',
            name='story_title_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
