# Generated by Django 3.0.3 on 2020-07-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0015_audio_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chappter',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='chappter',
            name='chapter_number',
        ),
    ]
