# Generated by Django 3.0.3 on 2020-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0016_auto_20200707_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_comments',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='audio_comments',
            name='chapter_number',
        ),
        migrations.AddField(
            model_name='chappter',
            name='chapter_name',
            field=models.CharField(default='not mentioned', max_length=40),
        ),
        migrations.AddField(
            model_name='chappter',
            name='chapter_number',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
