# Generated by Django 3.0.3 on 2020-07-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0018_auto_20200707_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chappter',
            old_name='user_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='chappter',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='chappter',
            name='user_count',
        ),
    ]
