# Generated by Django 3.0.3 on 2020-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0019_auto_20200707_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_chappter',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
