# Generated by Django 3.0.8 on 2020-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0021_auto_20200707_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_chappter',
            name='chapter_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='audio_story',
            name='story_title_pic',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='chappter',
            name='chapter_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_title_pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
