# Generated by Django 3.0.3 on 2020-07-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0026_remove_audio_story_story_title_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chappter',
            name='chapter_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
