# Generated by Django 3.0.3 on 2020-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0027_auto_20200709_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_story',
            name='story_title_pic',
            field=models.ImageField(default='not uploaded', upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio_chappter',
            name='chapter_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
